### ISSUE TITLE
Some pieces of snapshots

### ISSUE THREAD

**Issue by ekiyanov** [akavel/go-explorer-rescued#1]
Hi. 
HEre is docker container `saturnism/go-ide`

It has clonned go-explorer in ...
Im not sure how old is your snapshots and how old is copy in that container but could help

Thanks.

**Comment by akavel** [comment]
Awesome, thanks! :) I extracted the repo and pushed it as a new branch, "rescue", and made it the default branch. It seems a bit newer than the snapshot I had, cool, thanks! :smiley: Also, marked the old branch as "snapshot" in case somebody would still need it for some reasons. By the way, out of curiosity, are you also using go-explorer?

**Comment by akavel** [comment]
Update: I've asked @garyburd by email, and he re-published the sources in a read-only repository at the original path (https://github.com/garyburd/go-explorer)! :tada:
